//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Code.Code.Libaries.Net;

namespace Code.Libaries.Net.Packets.ForServer
{
    
    public class ChatPacket : BasePacket
    {

        public enum ChatType
        {
            GAME, Public, Private, Party, AddFriend, RemoveFriend
        }

        public ChatType type;
        public ushort FROM_SERVER_UnitID;
        public string text;
        public string User { get; set; }

        #region implemented abstract members of BasePacket

        protected override int GetOpCode()
        {
            return 25;
        }

        protected override void enSerialize(ByteStream bytestream)
        {
            bytestream.AddByte((int)type);
            if (type == ChatType.Private)
            {
                bytestream.AddString(User);
            }
            bytestream.AddShort(FROM_SERVER_UnitID);
            bytestream.AddString(text);
        }

        protected override void deSerialize(ByteStream bytestream)
        {
            type = (ChatType)bytestream.GetByte();
            if (type == ChatType.Private)
            {
                User = bytestream.GetString();
            }
            FROM_SERVER_UnitID = bytestream.GetUnsignedShort();
            text = bytestream.GetString();
        }

        #endregion
    }
}

