//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Code.Code.Libaries.Net.Packets
{
    public class UIInventoryInterfacePacket : BasePacket
    {
        public enum PacketType
        {
            ERROR,
            SHOW,
            HIDE,
            SetItem
        }

        public PacketType type {get;set;}
        public int UnitID { get; set; }
        public int Value { get; set; }
        public int X { get; set; }
        public int Y { get; set; }

        #region implemented abstract members of BasePacket

        protected override int GetOpCode()
        {
            return 52;
        }

        protected override void enSerialize(ByteStream bytestream)
        {
            bytestream.AddByte((int)type);
            bytestream.AddShort(UnitID);
            bytestream.AddShort(Value);
            bytestream.AddByte(X);
            bytestream.AddByte(Y);
        }

        protected override void deSerialize(ByteStream bytestream)
        {
            type = (PacketType) bytestream.GetByte();
            UnitID = bytestream.GetUnsignedShort();
            Value = bytestream.GetShort();
            X = bytestream.GetByte();
            Y = bytestream.GetByte();
        }

        #endregion
    }
}

